### ISSUE TITLE
Request: Extend documentation

### ISSUE THREAD

**Issue by v-lopez** [ihmcrobotics/ihmc_ros_diagnostics#6]
Hi, thanks for fixing https://github.com/ihmcrobotics/ihmc_ros_diagnostics/issues/5 so quickly.

Currently I am starting the logger without errors, I see it establishes some kind of connection with the running controller, because it prints these messages on the controller terminal:

```
Accepted client:  java.nio.channels.SocketChannel[connected local=/127.0.0.1:56485 remote=/127.0.0.1:60702]
```

And the logger has this output:

```
roslaunch ihmc_ros_diagnostics ihmc_logger.launch 
... logging to /home/user/.ros/log/6e1d1336-1a96-11e7-b914-0242ac110002/roslaunch-a3f9b4a8f486-14961.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://172.17.0.2:37017/

SUMMARY
========

PARAMETERS
 * /rosdistro: indigo
 * /rosversion: 1.11.21

NODES
  /
    IHMCLogger (ihmc_ros_java_adapter/gradlew)

ROS_MASTER_URI=http://172.17.0.2:11311

core service [/rosout] found
process[IHMCLogger-1]: started with pid [14979]
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:parseYaml UP-TO-DATE
:runJavaDelegate
Starting YoVariableLoggerDispatcher
[INFO] (NetworkParameters.java:38): Looking for network parameters in network parameters file at /home/user/.ihmc/IHMCNetworkParameters.ini
[INFO] (NetworkParameters.java:42): Found Network parameters file at /home/user/.ihmc/IHMCNetworkParameters.ini
[INFO] (NetworkParameters.java:69): Looking for network parameters in environment variables
[INFO] (NetworkParameters.java:70): Environment variables will override entries in the network parameters file.
[INFO] (YoVariableLoggerDispatcher.java:29): Listening on interface name:lo (lo)
Client started, waiting for announcements
New control session came online 5589530087520206847
New control session came online 6152198565964808191
Logging sesion 6152198565964808191
6152198565964808191
Cameras: []
Requesting handshake
[INFO] (KryoObjectClient.java:130): Success! Connected KryoClient to SCS at ip /127.0.0.1 on port 56322
Logging session started
New control session came online -6877278105971458049
Listening on /127.0.0.1:35912
Starting timestamp thread on /127.0.0.1:35912
> Building 50% > :runJavaDelegate
```
But there's nothing else. The logger doesn't appear when I execute `rosnode list` even though they are running on the same ROS master, and there are no new topics or services after starting it.

I have seen it creates a directory in `~/robotLogs/.20170406_071254_Toolbox_PlanarRegionBipedalFootstepPlannerVisualizerFactory/` but it doesn't seem to be increasing in size as I move the robot around, nor I can interpret the data inside.

Am I missing something?

**Comment by dljsjr** [comment]
@v-lopez By default the IHMC Logger does not record data from simulations (both SCS and Gazebo). This isn't a configuration flag that's currently exposed at runtime, it involves recompiling code, but we can investigate either enabling this by default or exposing this configuration in the .yaml or roslaunch for the whole body controller.

**Comment by v-lopez** [comment]
@dljsjr Thanks that would be very interesting. We are trying to determine why sometimes the valkyrie collapses when we command it, it happens both when walking and moving the upper body. Would you have some suggestion as to how to determine what is causing them?

I have also found out that roslaunch ihmc_valkyrie_ros remote_valkyrie_visualizer.launch gives us access to the variables in a GUI, but ideally we would like to have them published to a file so we can run automated tests and if there's a crash look at the logs oflfine.

**Comment by dljsjr** [comment]
@v-lopez The IHMC logger wouldn't be useful for this anyway, as it logs in a binary format without a well-defined API. The logs aren't designed to be interacted with programatically currently. We're rewriting the logging pipeline but that code probably won't make it in to the SRC since it's extremely not backwards compatible.

However, the logger would be useful for making the log files to send to us so we can assist with debugging the falls. So we'll definitely look in to exposing that configuration for you.

The remote visualizer can serialize whatever is in its current data buffer, though, to a lot of formats (including Matlab friendly formats). If you Disconnect the visualizer you can crop and export variables. This process isn't very well documented currently but I'll see if I can whip something up for you to get you started.

My guess would be something is causing the robot to think that it's falling/lost its balance, in which case it reverts to a "DO NOTHING" state (the same state that it's in when it's waiting for the hoist to be lowered). I know that OSRF is currently working on code to reattach the simulated harness for resetting the robot but I don't know how far they've gotten. You can use the search panel in the visualizer to look for a variable in the remote visualizer with "falling" in its name (I forget the exact name of the variable) and that signal should go high when the robot thinks it has lost its balance. This could be the result of over-aggressive maneuvers, physics loop hiccups, problems with simulated sensors, or even a controller bug. It's hard to say exactly.

**Comment by v-lopez** [comment]
Thanks a lot @dljsjr for your help. Hopefully with this information we'll work something out.
